export const instructors = [
  {
    id: "1",
    name: "Andrew williams",
    image: "   https://img-c.udemycdn.com/user/75x75/4851584_06aa_2.jpg",
    coursename: "Wordpress, seo",
    students: "145,834",
    coursesnum: "30",
  },
  {
    id: "2",
    name: "Brad schiff",
    image: "  https://img-c.udemycdn.com/user/75x75/5993622_f5da_2.jpg",
    coursename: "CSs ,Html",
    students: "194,937",
    coursesnum: "7",
  },
  {
    id: "3",
    name: "Daniel Scott",
    image: " https://img-c.udemycdn.com/user/75x75/11614232_b0fc.jpg",
    coursename: "Web Design,Css",
    students: "525,756",
    coursesnum: "30",
  },
  {
    id: "4",
    name: "Codee And Create",
    image: "https://img-c.udemycdn.com/user/75x75/5993622_f5da_2.jpg",
    coursename: "CSs,WebDevelopment",
    students: "52,497",
    coursesnum: "9",
  },
  {
    id: "5",
    name: "Christian Doru Brain",
    image: "https://img-c.udemycdn.com/user/75x75/342181_8b81_6.jpg",
    coursename: "Web Design ,Photoshop",
    students: "262,019",
    coursesnum: "9",
  },
  {
    id: "6",
    name: "Tanzeel Rehman",
    image: "https://img-c.udemycdn.com/user/75x75/5217450_8962_4.jpg",
    coursename: "Wordpress,Html",
    students: "125,774",
    coursesnum: "10",
  },
//   {
//     id: "",
//     name: "",
//     image: "",
//     coursename: "",
//     students: "",
//     coursesnum: "",
//   },
];
